- action: Terminate Pod
  actionner: kubernetes:terminate

- action: Disable outbound connections with Calico
  actionner: calico:networkpolicy

- action: Label Pod as Suspicious
  actionner: kubernetes:label
  parameters:
    labels:
      suspicious: "true"

- rule: Suspicious outbound connection
  match:
    rules:
      - Outbound Connection to Suspicious IPs
  actions:
    - action: Disable outbound connections with Calico
    - action: Terminate Pod
      parameters:
        grace_period_seconds: 20

- rule: Terminal shell in container 
  match:
    rules:
      - Terminal shell in container
    output_fields:
      - k8s.ns.name!=kube-system, k8s.ns.name!=falco
  actions:
    - action: Label Pod as Suspicious
