# Default values for falco-talon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  registry: docker.io
  repository: issif/falco-talon
  tag: latest
  pullPolicy: Always

podSecurityPolicy:
  create: false

podSecurityContext:
  runAsUser: 1234
  fsGroup: 1234

# One or more secrets to be used when pulling images
imagePullSecrets: []
# - registrySecretName

nameOverride: ""

extraEnv: {}

priorityClassName: ""

podAnnotations: {}

# listenAddress: 0.0.0.0
# listenPort: 2803

service:
  type: ClusterIP
  port: 2803
  annotations: {}
    # networking.gke.io/load-balancer-type: Internal

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: falco-talon.local
      paths:
        - path: /
          # -- pathType (e.g. ImplementationSpecific, Prefix, .. etc.)
          # pathType: Prefix

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

defaultNotifiers: # these notifiers will be enabled for all rules
  #  - slack
  - k8sevents

watchRules: true # reload if the rules file changes (default: true)

rulesFiles: # list of locale rules files to use, they will be concatenated into a single config map
  - rules.yaml
  - rules_override.yaml

deduplicationLeaderLease: true # in k8s only, create a lease for the leader election
# deduplicationTimeWindowSeconds: 5 # duration in seconds for the deduplication time window

printAllEvents: false # print in stdout all received events, not only those which match a rule

# See https://docs.falco-talon.org/docs/notifiers/list/ for the settings
notifiers:
  slack:
    # webhook_url: "https://hooks.slack.com/services/XXXX"
    # icon: "" # default: "https://upload.wikimedia.org/wikipedia/commons/2/26/Circaetus_gallicus_claw.jpg"
    # username: "" # default: "Falco Talon"
    footer: "" # default: "https://github.com/falco-talon/falco-talon"
    format: long # default: long
  webhook:
    url: ""
